### ISSUE TITLE
Flooding bakkesmod.log with unneccesary info

### ISSUE THREAD

**Issue by mgavin** [SoulDaMeep/PlatformDisplay#14]
https://github.com/SoulDaMeep/PlatformDisplay/blob/4c1a241022da4946b69a20bc8b3f459a223623cf/PlatformDisplay/PlatformDisplay.cpp#L269

on this line

**Comment by SoulDaMeep** [comment]
Will do in the morning. Will take some time to get approved by staff publicly tho.

**Comment by SoulDaMeep** [comment]
Removed line while updating other logs to be more specific to PlatformDisplay.
